spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=botuser
spring.datasource.password=botpass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

telegram.bot.token=8451645743:AAGTOZh19bsTDcxVdo0PAvJ2QU99mfh7Pdw

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
